server:
  port: 4000

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
          eventConsumerBufferSize: 10
          failureRateThreshold: 50
          minimumNumberOfCalls: 5
          automaticTransitionFromOpenToHalfOpenEnabled: true
          waitDurationInOpenState: 5s
          permittedNumberOfCallsInHalfOpenState: 3
          slidingWindowSize: 10
          slidingWindowType: COUNT_BASED

    instances:
      realtime-cb:
        baseConfig: default
        registerHealthIndicator: true
      daily-cb:
        baseConfig: default
        registerHealthIndicator: true
      hourly-cb:
        baseConfig: default
        registerHealthIndicator: true