server:
  port: 4000

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

resilience4j:
  circuitbreaker:
    configs:
      default:
        eventConsumerBufferSize: 10
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      wordMeaning-cb:
        registerHealthIndicator: true
        baseConfig: default
