spring:
  application:
    name: AnimeInfoAPI

server:
  port: 4002

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:4444/eureka/
